SELECT "PLAN_ID","START_DATE","WIP_NO","PLAN_QTY","LINE_ID","UNIT_NO","ITEM_NO","WERKS","DESCTION",
  "CREATE_DATE","CREATE_USERID","UPDATE_DATE","UPDATE_USERID","SIDE","CUSTOMER_NAME_CH",
  "MODULE_ITEM_NO","MODULE_ITEM_NAME","ONLINE_TIME","STATUS_NO","WIP_PLAN_QTY","END_TIME","SEQ","MODEL_NO","MATERIAL_DATE",
  "DELIVERY_DATE","CT","CHANGE_TIME","PREPARE_WIP_NO","AUTO_MEMO","APS_SEQ_NO","APS_WIP_MEMO","ERP_ORDER_STATUS","APS_UNIT_NO",
  "ERP_WIP_NO","APS_WIP_NO","APS_MACHINE_NO","PRE_APS_WIP_NO","PRE_ERP_WIP_NO","AFTER_APS_WIP_NO","AFTER_ERP_WIP_NO",
  "NOT_FINISH_MEMO","MMSTA","AFTER_START_DATE","NOT_FINISH_TYPE","EMERGENCY_QTY","EMERGENCY_DATE","PLAN_QTY_TOMORROW","WIP_TYPE",
  "WITHIN_GROUP_SEQ","FINISH_ITEM_NO","COMBINE_GROUP","COMBINE_WIP_NO"
  FROM CHMESDB."dbo"."PRODUCTION_PLAN"
  WHERE ("START_DATE" IS NOT NULL) AND ("START_DATE" >= '2024-01-03') 
  AND ((("UNIT_NO" IN (N'A', N'B', N'T', N'P')) = 1) OR (("UNIT_NO" IN (N'A', N'B', N'T', N'P')) IS NULL AND 1 IS NULL))
  -----                                         ~~~                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  
SELECT "PLAN_ID","START_DATE","WIP_NO","PLAN_QTY","LINE_ID","UNIT_NO","ITEM_NO","WERKS","DESCTION",
  "CREATE_DATE","CREATE_USERID","UPDATE_DATE","UPDATE_USERID","SIDE","CUSTOMER_NAME_CH",
  "MODULE_ITEM_NO","MODULE_ITEM_NAME","ONLINE_TIME","STATUS_NO","WIP_PLAN_QTY","END_TIME","SEQ","MODEL_NO","MATERIAL_DATE",
  "DELIVERY_DATE","CT","CHANGE_TIME","PREPARE_WIP_NO","AUTO_MEMO","APS_SEQ_NO","APS_WIP_MEMO","ERP_ORDER_STATUS","APS_UNIT_NO",
  "ERP_WIP_NO","APS_WIP_NO","APS_MACHINE_NO","PRE_APS_WIP_NO","PRE_ERP_WIP_NO","AFTER_APS_WIP_NO","AFTER_ERP_WIP_NO",
  "NOT_FINISH_MEMO","MMSTA","AFTER_START_DATE","NOT_FINISH_TYPE","EMERGENCY_QTY","EMERGENCY_DATE","PLAN_QTY_TOMORROW","WIP_TYPE",
  "WITHIN_GROUP_SEQ","FINISH_ITEM_NO","COMBINE_GROUP","COMBINE_WIP_NO"
  FROM CHMESDB."dbo"."PRODUCTION_PLAN"
  WHERE ("START_DATE" IS NOT NULL) AND ("START_DATE" >= '2024-01-03') 
  AND ((("UNIT_NO" IN (N'A', N'B', N'T', N'P'))) OR ("UNIT_NO" IS NULL AND 1 IS NULL)
  )
  